name = "CBR Libraries"

[files]
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/andrea_terminal.py" = "andrea_terminal.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/restapi.py" = "restapi.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_os.py" = "file_os.py"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_transfer.py" = "file_transfer.py"
"/ble_test.py" = "ble_test.py"

[js_modules.main]
"https://esm.run/micro-repl@0.5.1/serial" = "micro_repl"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/mqtt_library.js" = "mqtt_library"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/ble_library.js" = "ble_library"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/file_library.js" = "file_library"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/camera_library.js" = "camera"
"https://chrisrogers.pyscriptapps.com/cbr-libraries/latest/core/audio_library.js" = "audio"
